"""another one

Revision ID: 100e70f2ecb7
Revises: 2ad30e93146b
Create Date: 2025-05-23 22:47:38.479279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100e70f2ecb7'
down_revision = '2ad30e93146b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('document_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('document_filename')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
